from dataclasses import dataclass


@dataclass
class Case:
    in_data: object
    out_data: object


@dataclass
class Lab1Task12Data:
    file: str
    size: int
    is_sorted: bool


cases = [
    Case(
        in_data=Lab1Task12Data(file="./samples/sample_0.csv", size=13, is_sorted=True),
        out_data={
            "bc12": 32,
            "23": 30,
            "asswor": 28,
            "onke": 27,
            "2345": 25,
            "234567": 25,
            "aste": 23,
            "ichae": 23,
            "uss": 23,
            "etmei": 23,
            "ennife": 23,
            "uperma": 23,
            "00": 23,
        },
    ),
    Case(
        in_data=Lab1Task12Data(file="./samples/sample_0.csv", size=6, is_sorted=False),
        out_data={
            "bc12": 32,
            "23": 30,
            "asswor": 28,
            "onke": 27,
            "2345": 25,
            "234567": 25,
        },
    ),
    Case(
        in_data=Lab1Task12Data(file="./samples/sample_1.csv", size=24, is_sorted=False),
        out_data={
            "arle": 33,
            "eorg": 32,
            "234": 32,
            "es": 32,
            "asebal": 32,
            "ennife": 31,
            "onke": 30,
            "etmei": 30,
            "1111": 29,
            "2345": 28,
            "homa": 28,
            "uss": 28,
            "as": 28,
            "ocke": 27,
            "uc": 27,
            "9696": 27,
            "ange": 26,
            "bc12": 26,
            "aste": 26,
            "ille": 26,
            "234567": 26,
            "00": 25,
            "wert": 25,
            "23": 25,
        },
    ),
    Case(
        in_data=Lab1Task12Data(file="./samples/sample_1.csv", size=21, is_sorted=True),
        out_data={
            "arle": 33,
            "eorg": 32,
            "234": 32,
            "es": 32,
            "asebal": 32,
            "ennife": 31,
            "onke": 30,
            "etmei": 30,
            "1111": 29,
            "2345": 28,
            "homa": 28,
            "uss": 28,
            "as": 28,
            "ocke": 27,
            "uc": 27,
            "9696": 27,
            "ange": 26,
            "bc12": 26,
            "aste": 26,
            "ille": 26,
            "234567": 26,
        },
    ),
    Case(
        in_data=Lab1Task12Data(file="./samples/sample_2.csv", size=10, is_sorted=True),
        out_data={
            "rang": 46,
            "occe": 44,
            "9696": 44,
            "sshol": 43,
            "tarwar": 42,
            "asebal": 41,
            "item": 41,
            "ex": 40,
            "ell": 39,
            "23": 39,
        },
    ),
    Case(
        in_data=Lab1Task12Data(file="./samples/sample_2.csv", size=4, is_sorted=False),
        out_data={"rang": 46, "occe": 44, "9696": 44, "sshol": 43},
    ),
    Case(
        in_data=Lab1Task12Data(file="./samples/sample_3.csv", size=50, is_sorted=True),
        out_data={
            "ille": 47,
            "laye": 42,
            "usti": 42,
            "ndre": 40,
            "arlbor": 38,
            "uc": 35,
            "ootbal": 35,
            "leas": 35,
            "ardcor": 34,
            "nigh": 33,
            "ishin": 32,
            "idnigh": 32,
            "azws": 32,
            "amme": 31,
            "anthe": 31,
            "eorg": 31,
            "lowm": 31,
            "ell": 30,
            "lowjo": 30,
            "occe": 30,
            "1111": 30,
            "offe": 30,
            "harli": 30,
            "iabl": 29,
            "asswor": 29,
            "ecre": 29,
            "onste": 29,
            "xxxx": 29,
            "umme": 29,
            "orsch": 29,
            "orvett": 29,
            "antie": 28,
            "aaaa": 28,
            "inte": 28,
            "ichae": 28,
            "osep": 28,
            "ex": 28,
            "rando": 28,
            "noop": 28,
            "akot": 27,
            "igge": 27,
            "anan": 27,
            "234567": 27,
            "igtit": 27,
            "ompute": 27,
            "asebal": 27,
            "9696": 27,
            "agle": 27,
            "etmei": 27,
            "aste": 27,
        },
    ),
    Case(
        in_data=Lab1Task12Data(file="./samples/sample_3.csv", size=72, is_sorted=True),
        out_data={
            "ille": 47,
            "laye": 42,
            "usti": 42,
            "ndre": 40,
            "arlbor": 38,
            "uc": 35,
            "ootbal": 35,
            "leas": 35,
            "ardcor": 34,
            "nigh": 33,
            "ishin": 32,
            "idnigh": 32,
            "azws": 32,
            "amme": 31,
            "anthe": 31,
            "eorg": 31,
            "lowm": 31,
            "ell": 30,
            "lowjo": 30,
            "occe": 30,
            "1111": 30,
            "offe": 30,
            "harli": 30,
            "iabl": 29,
            "asswor": 29,
            "ecre": 29,
            "onste": 29,
            "xxxx": 29,
            "umme": 29,
            "orsch": 29,
            "orvett": 29,
            "antie": 28,
            "aaaa": 28,
            "inte": 28,
            "ichae": 28,
            "osep": 28,
            "ex": 28,
            "rando": 28,
            "noop": 28,
            "akot": 27,
            "igge": 27,
            "anan": 27,
            "234567": 27,
            "igtit": 27,
            "ompute": 27,
            "asebal": 27,
            "9696": 27,
            "agle": 27,
            "etmei": 27,
            "aste": 27,
            "coob": 26,
            "mand": 26,
            "sd": 26,
            "ondo": 26,
            "andal": 26,
            "teve": 26,
            "ober": 26,
            "sdfg": 26,
            "olfe": 26,
            "inge": 26,
            "alco": 26,
            "2121": 26,
            "oobo": 26,
            "ello": 26,
            "6666": 26,
            "essic": 26,
            "cema": 26,
            "or": 26,
            "ilve": 26,
            "arne": 26,
            "hri": 26,
            "elcom": 26,
        },
    ),
]